# Generated by Django 4.1.1 on 2022-12-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Password',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
