# Generated by Django 4.1.1 on 2022-12-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerApi', '0002_member_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Password',
        ),
    ]
