# Generated by Django 4.1.1 on 2022-12-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerApi', '0003_remove_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='MobileNo',
            field=models.IntegerField(unique=True),
        ),
    ]
