# Generated by Django 4.1.1 on 2022-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerApi', '0004_alter_member_email_alter_member_mobileno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberId', models.IntegerField()),
                ('BatchTiming', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentId', models.IntegerField(unique=True)),
                ('MemberId', models.IntegerField()),
                ('PaymentAmount', models.FloatField()),
                ('PaymentMethod', models.CharField(max_length=20)),
                ('PaymentDate', models.DateField()),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
